### PR TITLE
for compatibility with Cloudera Manager

### PR DESCRIPTION
**Pull request by storysj**

### CODE REVIEW

**Comment by cpenner461** [comment]
Does this break compatibility without CM?

**Comment by storysj** [comment]
It shouldn't. Kerberos doesn't create TCP connections by default, but it's definitely something that it's capable of. Removing the kdc_ports option in the [realms] section should have no effect, since the [kdcdefaults] section sets the defaults for all realms.

**Comment by clarkperkins** [comment]
:+1:

**Comment by storysj** [comment]
someone else will have to merge this, I don't have write access

**Pull request merged**
